version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - doc_app_network
  
  doc_app_server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: doc_app_server
    volumes:
      - .:/var/www
    networks:
      - doc_app_network
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1

networks:
  doc_app_network:
    driver: bridge
