version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
  
  doc_app_server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: doc_app_server
    volumes:
      - .:/var/www
    networks:
      - docker-network

networks:
  docker-network:
    external: true
      
